source 'https://rubygems.org'

gem 'rails', '4.1.1'

gem 'spring', :group => :development

gem 'jquery-rails'

gem 'sqlite3'

gem 'tzinfo-data'

gem 'rack-cors', :require=> 'rack/cors'

gem 'active_model_serializers'

gem 'ice_cube'

gem 'rabl'
# Also add either `oj` or `yajl-ruby` as the JSON parser
gem 'oj'

gem 'devise'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bootstrap inclusion
gem 'bootstrap-sass', '~> 3.2.0'

# Only install on UNIX platforms
gem 'therubyracer', :platform => :ruby

gem 'autoprefixer-rails'

# Bower for front end dependencies
gem 'bower-rails'
gem 'angular-rails-templates'

# For debugging
gem 'byebug'

gem 'uglifier'
