source 'http://rubygems.org'

gem 'rails', '4.1.1'

gem 'spring', :group => :development

gem 'jquery-rails'

gem 'sqlite3'

gem 'tzinfo-data'

gem 'rack-cors', :require=> 'rack/cors'

gem 'active_model_serializers'

gem 'ice_cube'

gem 'rabl'
# Also add either `oj` or `yajl-ruby` as the JSON parser
gem 'oj'

# Users and admins
gem 'devise'

# gem 'omniauth'
# gem 'omniauth-facebook'
# gem 'omniauth-google'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bootstrap inclusion
gem 'bootstrap-sass', '~> 3.2.0'

# Only install on UNIX platforms
gem 'therubyracer', :platform => :ruby

gem 'autoprefixer-rails'

# Bower for front end dependencies
gem 'bower-rails'
gem 'angular-rails-templates'

# HTTP requests within the app
gem 'rest-client'

# Debugging
gem 'byebug'

# Minimizing JS
gem 'uglifier'

# Postgres
gem 'pg'

# Foreign key constrains for databases
gem 'foreigner', '~> 1.7.1'

# Soft deletes
gem "paranoia", "~> 2.0"

# Automatic inlining of styles on email templates
gem "roadie", "~> 2.4.0"

# Automatic grids
gem "wice_grid", '~> 3.4.10'
# WiceGrid needs it
gem "coffee-rails"