// Run this SQL script to add Facebook App to django-allauth database

UPDATE django_site SET DOMAIN = '127.0.0.1:8000', name = 'TeamHuddle' WHERE id=1;
INSERT INTO socialaccount_socialapp (provider, name, secret, client_id, `key`)
VALUES ("facebook", "Facebook", "fdd2e0dc99cd9e4b936484334822f33b", "859393764120770", '');
INSERT INTO socialaccount_socialapp_sites (socialapp_id, site_id) VALUES (1,1);